/* ============================================================
   HiveBooks — book catalogue (fiction, ages 4–13)
   Levels 1–7, from ages 4–6 up to ages 11–13 (see LEVEL_META).
   Each book carries a subtype (`genre`), an age recommendation and a
   Nectar value earned for finishing it. HiveScore comes only from real
   reader ratings (no seeded/placeholder scores).
   ============================================================ */

const SAMPLE_BOOKS = [
  // ---------- Level 1 · Ages 4–6 ----------
  { id: "f1", level: 1, title: "Frog and Toad Are Friends", shortTitle: "Frog & Toad", author: "Arnold Lobel",
    genres: ["Friendship", "Humor"], ageAlone: 6, ageAdult: 4, nectar: 10,
    blurb: "Two best friends share gentle, funny little adventures together." },
  { id: "f2", level: 1, title: "Mercy Watson to the Rescue", shortTitle: "Mercy Watson", author: "Kate DiCamillo",
    genres: ["Humor", "Animals"], ageAlone: 6, ageAdult: 4, nectar: 10,
    blurb: "A butter-loving pig gets into hilarious trouble around the house." },
  { id: "f3", level: 1, title: "Narwhal: Unicorn of the Sea", shortTitle: "Narwhal", author: "Ben Clanton",
    genres: ["Humor", "Friendship", "Animals"], ageAlone: 6, ageAdult: 4, nectar: 10,
    blurb: "A happy narwhal and a grumpy jellyfish become the silliest of pals." },
  { id: "f4", level: 1, title: "Owl Diaries: Eva's Treetop Festival", shortTitle: "Owl Diaries", author: "Rebecca Elliott",
    genres: ["Animals", "Friendship"], ageAlone: 6, ageAdult: 5, nectar: 10,
    blurb: "Eva the owl plans a big festival and learns to ask for help." },
  { id: "f5", level: 1, title: "The Princess in Black", shortTitle: "Princess in Black", author: "Shannon & Dean Hale",
    genres: ["Fantasy", "Humor"], ageAlone: 6, ageAdult: 4, nectar: 10,
    blurb: "A proper princess has a secret: she's also a monster-fighting hero!" },
  { id: "f6", level: 1, title: "Elephant & Piggie: There Is a Bird on Your Head!", shortTitle: "Elephant & Piggie", author: "Mo Willems",
    genres: ["Humor", "Friendship"], ageAlone: 5, ageAdult: 4, nectar: 10,
    blurb: "Gerald and Piggie panic — and giggle — over a bird (or two)." },

  // ---------- Level 2 · Ages 6–8 ----------
  { id: "m1", level: 2, title: "Magic Tree House: Dinosaurs Before Dark", shortTitle: "Magic Tree House", author: "Mary Pope Osborne",
    genres: ["Adventure", "Fantasy"], ageAlone: 7, ageAdult: 6, nectar: 20,
    blurb: "A magic treehouse whisks Jack and Annie back to the age of dinosaurs." },
  { id: "m2", level: 2, title: "Dragon Masters: Rise of the Earth Dragon", shortTitle: "Dragon Masters", author: "Tracey West",
    genres: ["Fantasy", "Adventure"], ageAlone: 7, ageAdult: 6, nectar: 20,
    blurb: "A young boy learns to train and bond with a powerful dragon." },
  { id: "m3", level: 2, title: "The Kingdom of Wrenly: The Lost Stone", shortTitle: "Kingdom of Wrenly", author: "Jordan Quinn",
    genres: ["Fantasy", "Adventure"], ageAlone: 7, ageAdult: 6, nectar: 20,
    blurb: "A prince and his friend quest across a magical kingdom for a lost gem." },
  { id: "m4", level: 2, title: "The Notebook of Doom: Rise of the Balloon Goons", shortTitle: "Notebook of Doom", author: "Troy Cummings",
    genres: ["Horror", "Humor"], ageAlone: 7, ageAdult: 6, nectar: 20,
    warning: { level: 1, text: "Cartoon monsters — more silly than scary." },
    blurb: "A boy discovers a notebook full of monsters — and they're real!" },
  { id: "m5", level: 2, title: "The Magic School Bus: Inside the Earth", shortTitle: "Magic School Bus", author: "Joanna Cole",
    genres: ["Science", "Adventure"], ageAlone: 8, ageAdult: 6, nectar: 20,
    blurb: "Ms. Frizzle's class takes a wild field trip deep into the ground." },

  // ---------- Level 3 · Ages 7–9 ----------
  { id: "c1", level: 3, title: "My Father's Dragon", shortTitle: "My Father's Dragon", author: "Ruth Stiles Gannett",
    genres: ["Fantasy", "Adventure", "Animals"], ageAlone: 8, ageAdult: 6, nectar: 30,
    blurb: "A brave boy sails to Wild Island to rescue a baby dragon." },
  { id: "c2", level: 3, title: "The Boxcar Children", shortTitle: "Boxcar Children", author: "Gertrude Chandler Warner",
    genres: ["Mystery", "Adventure"], ageAlone: 8, ageAdult: 7, nectar: 30,
    blurb: "Four orphaned siblings make a home in an old boxcar and solve mysteries." },
  { id: "c3", level: 3, title: "Fantastic Mr. Fox", shortTitle: "Fantastic Mr. Fox", author: "Roald Dahl",
    genres: ["Animals", "Humor", "Adventure"], ageAlone: 8, ageAdult: 6, nectar: 30,
    blurb: "A clever fox outwits three nasty farmers to feed his family." },
  { id: "c4", level: 3, title: "James and the Giant Peach", shortTitle: "James & the Peach", author: "Roald Dahl",
    genres: ["Fantasy", "Adventure"], ageAlone: 8, ageAdult: 7, nectar: 30,
    warning: { level: 1, text: "James's aunts are cruel to him, and a few moments are gruesome." },
    blurb: "A lonely boy sails the ocean inside a giant peach with buggy friends." },
  { id: "c5", level: 3, title: "The Land of Stories: The Wishing Spell", shortTitle: "Land of Stories", author: "Chris Colfer",
    genres: ["Fairy Tale", "Fantasy", "Adventure"], ageAlone: 9, ageAdult: 7, nectar: 30,
    blurb: "Twins fall into a fairy-tale world and race to find a way home." },

  // ---------- Level 4 · Ages 8–10 ----------
  { id: "d1", level: 4, title: "Matilda", shortTitle: "Matilda", author: "Roald Dahl",
    genres: ["Fantasy", "Humor"], ageAlone: 8, ageAdult: 6, nectar: 40,
    warning: { level: 1, text: "The Trunchbull is very cruel to children." },
    blurb: "A brilliant little girl with secret powers outsmarts awful grown-ups." },
  { id: "d2", level: 4, title: "Charlie and the Chocolate Factory", shortTitle: "Charlie & Chocolate", author: "Roald Dahl",
    genres: ["Fantasy", "Humor"], ageAlone: 8, ageAdult: 6, nectar: 40,
    warning: { level: 1, text: "Naughty kids meet some nasty (but funny) fates." },
    blurb: "A golden ticket wins Charlie a tour of a wondrous, weird chocolate factory." },
  { id: "d3", level: 4, title: "The BFG", shortTitle: "The BFG", author: "Roald Dahl",
    genres: ["Fantasy", "Humor", "Adventure"], ageAlone: 8, ageAdult: 6, nectar: 40,
    warning: { level: 1, text: "The bad giants eat people, though it's mostly played for laughs." },
    blurb: "A friendly giant and a brave girl team up to stop the nasty giants." },
  { id: "d4", level: 4, title: "The Wild Robot", shortTitle: "The Wild Robot", author: "Peter Brown",
    genres: ["Sci-Fi", "Animals", "Survival"], ageAlone: 8, ageAdult: 6, nectar: 40,
    warning: { level: 1, text: "Animals die, and there are some sad moments." },
    blurb: "A robot washes ashore on a wild island and learns how to belong." },
  { id: "d5", level: 4, title: "The Chocolate Touch", shortTitle: "Chocolate Touch", author: "Patrick Skene Catling",
    genres: ["Fantasy", "Humor"], ageAlone: 8, ageAdult: 7, nectar: 40,
    blurb: "Everything a boy tastes turns to chocolate — and it's not so sweet." },
  { id: "d6", level: 4, title: "Ella Enchanted", shortTitle: "Ella Enchanted", author: "Gail Carson Levine",
    genres: ["Fairy Tale", "Fantasy", "Humor"], ageAlone: 9, ageAdult: 7, nectar: 40,
    blurb: "Cursed to always obey, Ella sets out to break the spell and be free." },

  // ---------- Level 5 · Ages 9–11 ----------
  { id: "e1", level: 5, title: "Harry Potter and the Sorcerer's Stone", shortTitle: "Harry Potter", author: "J.K. Rowling",
    genres: ["Fantasy", "Adventure", "Mystery"], ageAlone: 9, ageAdult: 7, nectar: 50,
    warning: { level: 2, text: "A frightening villain and some scary moments near the end." },
    blurb: "An orphan discovers he's a wizard and heads off to a school of magic." },
  { id: "e2", level: 5, title: "Percy Jackson: The Lightning Thief", shortTitle: "Percy Jackson", author: "Rick Riordan",
    genres: ["Mythology", "Fantasy", "Adventure"], ageAlone: 9, ageAdult: 8, nectar: 50,
    warning: { level: 2, text: "Monster fights and moments of real danger." },
    blurb: "A boy learns he's a demigod and races to stop a war among the gods." },
  { id: "e3", level: 5, title: "The Lion, the Witch and the Wardrobe", shortTitle: "Narnia", author: "C.S. Lewis",
    genres: ["Fantasy", "Adventure"], ageAlone: 9, ageAdult: 7, nectar: 50,
    warning: { level: 1, text: "A battle, and a beloved character is killed before coming back." },
    blurb: "Four siblings step through a wardrobe into a frozen magical land." },
  { id: "e4", level: 5, title: "Hatchet", shortTitle: "Hatchet", author: "Gary Paulsen",
    genres: ["Survival", "Adventure"], ageAlone: 10, ageAdult: 8, nectar: 50,
    warning: { level: 3, text: "A plane crash and injuries, and a dark moment where Brian loses hope and hurts himself." },
    blurb: "After a plane crash, a boy must survive alone in the wilderness." },
  { id: "g1", level: 5, title: "The Hobbit", shortTitle: "The Hobbit", author: "J.R.R. Tolkien",
    genres: ["Fantasy", "Adventure"], ageAlone: 10, ageAdult: 8, nectar: 50,
    warning: { level: 1, text: "Battles, a dragon, and a very creepy giant-spider scene." },
    blurb: "A cozy hobbit joins a band of dwarves on a quest to win back dragon gold." },
  { id: "g4", level: 5, title: "Redwall", shortTitle: "Redwall", author: "Brian Jacques",
    genres: ["Fantasy", "Animals", "Adventure"], ageAlone: 10, ageAdult: 9, nectar: 50,
    warning: { level: 2, text: "Animal characters fight in battles, and some are killed." },
    blurb: "Brave mice defend their peaceful abbey from a fearsome rat warlord." },
  { id: "e5", level: 5, title: "How to Train Your Dragon", shortTitle: "How to Train Your Dragon", author: "Cressida Cowell",
    genres: ["Humor", "Fantasy", "Animals"], ageAlone: 9, ageAdult: 7, nectar: 50,
    warning: { level: 1, text: "Vikings and dragons scrap a lot, but it's all very silly." },
    blurb: "A hopeless young Viking must train a very unimpressive dragon." },
  { id: "e6", level: 5, title: "The Spiderwick Chronicles: The Field Guide", shortTitle: "Spiderwick", author: "Holly Black & Tony DiTerlizzi",
    genres: ["Fantasy", "Horror", "Adventure"], ageAlone: 9, ageAdult: 8, nectar: 50,
    warning: { level: 2, text: "The fairies here are nasty and a bit frightening." },
    blurb: "Three siblings find a field guide to the hidden fairy world next door." },

  // ---------- Level 6 · Ages 10–12 ----------
  { id: "g2", level: 6, title: "A Wrinkle in Time", shortTitle: "A Wrinkle in Time", author: "Madeleine L'Engle",
    genres: ["Sci-Fi", "Fantasy", "Adventure"], ageAlone: 10, ageAdult: 8, nectar: 60,
    warning: { level: 1, text: "A creepy villain who controls people's minds." },
    blurb: "Meg travels across space and time to rescue her missing father." },
  { id: "g3", level: 6, title: "The Westing Game", shortTitle: "The Westing Game", author: "Ellen Raskin",
    genres: ["Mystery", "Humor"], ageAlone: 10, ageAdult: 9, nectar: 60,
    blurb: "Sixteen heirs race to solve a puzzling millionaire's final game." },
  { id: "g5", level: 6, title: "Artemis Fowl", shortTitle: "Artemis Fowl", author: "Eoin Colfer",
    genres: ["Fantasy", "Sci-Fi", "Adventure"], ageAlone: 10, ageAdult: 9, nectar: 60,
    warning: { level: 2, text: "A kidnapping and some violence, mostly played for fun." },
    blurb: "A boy genius takes on a high-tech underground world of fairies." },
  { id: "g6", level: 6, title: "Amari and the Night Brothers", shortTitle: "Amari", author: "B.B. Alston",
    genres: ["Fantasy", "Adventure", "Mystery"], ageAlone: 10, ageAdult: 9, nectar: 60,
    warning: { level: 2, text: "Magical danger, a missing brother, and prejudice against the hero." },
    blurb: "Amari joins a secret bureau of magic to find her missing brother." },
  { id: "g7", level: 6, title: "Keeper of the Lost Cities", shortTitle: "Keeper of Lost Cities", author: "Shannon Messenger",
    genres: ["Fantasy", "Adventure", "Mystery"], ageAlone: 10, ageAdult: 9, nectar: 60,
    warning: { level: 1, text: "Kidnapping and danger, especially later in the series." },
    blurb: "A telepathic girl discovers she belongs to a hidden elvin world." },
  { id: "g8", level: 6, title: "The City of Ember", shortTitle: "City of Ember", author: "Jeanne DuPrau",
    genres: ["Sci-Fi", "Mystery", "Adventure"], ageAlone: 10, ageAdult: 9, nectar: 60,
    warning: { level: 2, text: "A dying city, and children in real danger." },
    blurb: "Two kids search for a way out of a dying underground city." },
  { id: "h1", level: 6, title: "Wings of Fire: The Dragonet Prophecy", shortTitle: "Wings of Fire", author: "Tui T. Sutherland",
    genres: ["Fantasy", "Animals", "Adventure"], ageAlone: 11, ageAdult: 9, nectar: 60,
    warning: { level: 3, text: "A war between dragon tribes — dragons are wounded and killed." },
    blurb: "Five young dragons are raised to end a war they never chose." },
  { id: "g9", level: 6, title: "Fablehaven", shortTitle: "Fablehaven", author: "Brandon Mull",
    genres: ["Fantasy", "Adventure"], ageAlone: 10, ageAdult: 8, nectar: 60,
    warning: { level: 2, text: "Dangerous magical creatures and moments of real peril." },
    blurb: "A brother and sister find their grandpa's secret preserve for magical creatures." },
  { id: "g10", level: 6, title: "Serafina and the Black Cloak", shortTitle: "Serafina", author: "Robert Beatty",
    genres: ["Horror", "Mystery", "Fantasy"], ageAlone: 10, ageAdult: 9, nectar: 60,
    warning: { level: 3, text: "Children vanish one by one, and the villain is genuinely creepy." },
    blurb: "A girl living secretly in a grand mansion hunts whoever is taking the children." },
  { id: "g11", level: 6, title: "Ghost", shortTitle: "Ghost", author: "Jason Reynolds",
    genres: ["Realistic", "Sports"], ageAlone: 10, ageAdult: 9, nectar: 60,
    warning: { level: 2, text: "Ghost's father once shot at him and his mother, and he struggles with anger." },
    blurb: "A boy who runs from his past finds a place on an elite track team." },
  { id: "g12", level: 6, title: "The Last Kids on Earth", shortTitle: "Last Kids on Earth", author: "Max Brallier",
    genres: ["Humor", "Horror", "Adventure"], ageAlone: 10, ageAdult: 8, nectar: 60,
    warning: { level: 2, text: "A monster apocalypse with zombies, all played for laughs." },
    blurb: "A boy and his friends battle monsters in a zombie apocalypse treehouse." },

  // ---------- Level 7 · Ages 11–13 ----------
  { id: "h2", level: 7, title: "Eragon", shortTitle: "Eragon", author: "Christopher Paolini",
    genres: ["Fantasy", "Adventure"], ageAlone: 12, ageAdult: 10, nectar: 70,
    warning: { level: 3, text: "Battle violence, some gore, and the death of family." },
    blurb: "A farm boy finds a dragon egg and becomes the last Dragon Rider." },
  { id: "h3", level: 7, title: "Ranger's Apprentice: The Ruins of Gorlan", shortTitle: "Ranger's Apprentice", author: "John Flanagan",
    genres: ["Adventure", "Fantasy"], ageAlone: 11, ageAdult: 9, nectar: 70,
    warning: { level: 2, text: "Battles, war and violence." },
    blurb: "A small boy trains in secret as a Ranger to defend his kingdom." },
  { id: "h4", level: 7, title: "Nevermoor: The Trials of Morrigan Crow", shortTitle: "Nevermoor", author: "Jessica Townsend",
    genres: ["Fantasy", "Mystery", "Humor"], ageAlone: 11, ageAdult: 9, nectar: 70,
    warning: { level: 2, text: "Scary creatures and a menacing villain." },
    blurb: "A cursed girl escapes her fate and faces trials in a magical city." },
  { id: "h5", level: 7, title: "The Mysterious Benedict Society", shortTitle: "Benedict Society", author: "Trenton Lee Stewart",
    genres: ["Mystery", "Adventure"], ageAlone: 11, ageAdult: 9, nectar: 70,
    warning: { level: 1, text: "Mind control and moments of danger." },
    blurb: "Four gifted kids pass strange tests and go undercover as spies." },
  { id: "h6", level: 7, title: "A Series of Unfortunate Events: The Bad Beginning", shortTitle: "Unfortunate Events", author: "Lemony Snicket",
    genres: ["Mystery", "Humor"], ageAlone: 11, ageAdult: 8, nectar: 70,
    warning: { level: 2, text: "The children's parents die, and a villain schemes to marry a 14-year-old." },
    blurb: "Three orphans outwit a dreadful villain after their fortune." },
  { id: "h7", level: 7, title: "The Golden Compass", shortTitle: "Golden Compass", author: "Philip Pullman",
    genres: ["Fantasy", "Adventure", "Animals"], ageAlone: 11, ageAdult: 10, nectar: 70,
    warning: { level: 4, text: "Children are kidnapped and cut away from their souls, and one of them dies. The series is also strongly critical of organized religion. Worth talking about with a parent." },
    blurb: "Lyra journeys to the frozen North to rescue kidnapped children." },
  { id: "h8", level: 7, title: "Gregor the Overlander", shortTitle: "Gregor", author: "Suzanne Collins",
    genres: ["Fantasy", "Adventure"], ageAlone: 11, ageAdult: 9, nectar: 70,
    warning: { level: 2, text: "A war between humans and giant rats, with battles and deaths." },
    blurb: "A boy falls through a grate into a hidden world far beneath New York." },
  { id: "h9", level: 7, title: "Skulduggery Pleasant", shortTitle: "Skulduggery Pleasant", author: "Derek Landy",
    genres: ["Fantasy", "Horror", "Humor"], ageAlone: 11, ageAdult: 10, nectar: 70,
    warning: { level: 2, text: "A murder mystery with a walking skeleton and some creepy villains." },
    blurb: "A girl teams up with a wisecracking skeleton detective to solve a murder." },
  { id: "h10", level: 7, title: "Aru Shah and the End of Time", shortTitle: "Aru Shah", author: "Roshani Chokshi",
    genres: ["Mythology", "Fantasy", "Humor"], ageAlone: 11, ageAdult: 9, nectar: 70,
    warning: { level: 1, text: "Mythological monsters and moments of danger." },
    blurb: "Aru lights a cursed lamp and must save the world with Hindu gods' help." },
  { id: "h11", level: 7, title: "The False Prince", shortTitle: "The False Prince", author: "Jennifer A. Nielsen",
    genres: ["Adventure", "Mystery"], ageAlone: 11, ageAdult: 10, nectar: 70,
    warning: { level: 2, text: "A ruthless plot with violence, and a boy is killed." },
    blurb: "An orphan is forced to compete to impersonate a long-lost prince." },
  { id: "h12", level: 7, title: "The Girl Who Drank the Moon", shortTitle: "Girl Who Drank the Moon", author: "Kelly Barnhill",
    genres: ["Fantasy", "Fairy Tale"], ageAlone: 11, ageAdult: 9, nectar: 70,
    warning: { level: 2, text: "A village leaves babies in the forest as a sacrifice, and there are sad moments." },
    blurb: "A witch accidentally feeds a baby moonlight and fills her with magic." },
  { id: "h13", level: 7, title: "Watership Down", shortTitle: "Watership Down", author: "Richard Adams",
    genres: ["Animals", "Adventure"], ageAlone: 12, ageAdult: 10, nectar: 70,
    warning: { level: 3, text: "Rabbits are hunted, wounded and killed. Some scenes are genuinely frightening." },
    blurb: "A band of rabbits flees their doomed warren to find a new home." },
];

/* Similarity links between adjacent levels — "if you liked this, try that".
   Each entry is [younger-level id, older-level id, why-they're-connected].
   The reason is shown in the hover tooltip on the skill tree. */
const CONNECTIONS = [
  // Level 1 → Level 2
  ["f1", "m1", "gentle, cozy adventures"],
  ["f2", "m4", "silly laugh-out-loud stories"],
  ["f3", "m5", "funny science and sea creatures"],
  ["f4", "m3", "animal friends in a magical world"],
  ["f5", "m2", "brave heroes and dragons"],
  ["f5", "m3", "fantasy kingdoms and quests"],
  ["f6", "m4", "pure comedy and goofy characters"],
  // Level 2 → Level 3
  ["m1", "c1", "quests to faraway places"],
  ["m1", "c2", "exploring and solving mysteries"],
  ["m2", "c1", "dragons!"],
  ["m2", "c5", "big magical worlds"],
  ["m3", "c5", "fairy-tale quests"],
  ["m4", "c4", "quirky, slightly spooky adventures"],
  ["m5", "c3", "clever animals and nature"],
  // Level 3 → Level 4
  ["c1", "d3", "kids who befriend amazing creatures"],
  ["c2", "d4", "being resourceful and surviving"],
  ["c3", "d1", "more from Roald Dahl"],
  ["c3", "d4", "clever animals and nature"],
  ["c4", "d2", "more from Roald Dahl"],
  ["c4", "d3", "more from Roald Dahl"],
  ["c4", "d5", "magical food mischief"],
  ["c5", "d6", "fairy tales retold"],
  // Level 4 → Level 5
  ["d1", "e1", "gifted kids who discover magic"],
  ["d2", "e1", "an ordinary kid pulled into a magical world"],
  ["d2", "e3", "stepping into a wondrous world"],
  ["d3", "e3", "giants and magical lands"],
  ["d3", "g1", "unlikely heroes on enormous journeys"],
  ["d4", "e4", "surviving all on your own"],
  ["d4", "g4", "brave animal heroes in the wild"],
  ["d5", "e1", "magic in everyday life"],
  ["d6", "e2", "curses, quests and destiny"],
  ["d3", "e5", "funny stories about befriending big creatures"],
  ["d6", "e3", "classic fantasy adventure"],
  ["d6", "e6", "fairies who aren't as nice as they look"],
  ["d6", "g1", "classic fantasy adventure"],
  // Level 5 → Level 6
  ["e1", "g6", "secret magical organizations"],
  ["e1", "g7", "hidden magical worlds"],
  ["e1", "g3", "secrets and clues to piece together"],
  ["e2", "g5", "myths meet high-tech"],
  ["e2", "g6", "young heroes with big destinies"],
  ["e3", "g2", "portals to other worlds"],
  ["e4", "g8", "escape and survival"],
  ["g1", "g5", "quests full of treasure and trickery"],
  ["g1", "g7", "huge fantasy worlds to get lost in"],
  ["g1", "h1", "dragons and epic quests"],
  ["g4", "g7", "big worlds with deep lore and lots of characters"],
  ["g4", "h1", "epic animal fantasy"],
  ["e5", "h1", "dragons, dragons, dragons"],
  ["e6", "g5", "fairies with a dangerous side"],
  ["e3", "g9", "a magical world hidden right next door"],
  ["e1", "g10", "a hidden child and dark magic"],
  ["e4", "g11", "a kid facing something huge on his own"],
  ["e2", "g12", "monster fights, but funny"],
  // Level 6 → Level 7
  ["h1", "h2", "dragons and the riders who train them"],
  ["g2", "h7", "journeys between worlds"],
  ["g6", "h3", "training hard to become something special"],
  ["g5", "h4", "sharp wit and secret worlds"],
  ["g5", "h6", "dark humor and terrible villains"],
  ["g6", "h4", "secret magical societies"],
  ["g7", "h4", "hidden magical worlds"],
  ["g3", "h5", "puzzles and clever tests"],
  ["g3", "h6", "funny, twisty mysteries"],
  ["g8", "h5", "kids solving a dangerous puzzle"],
  ["g8", "h8", "hidden worlds deep beneath the ground"],
  ["g6", "h9", "secret magical worlds with sharp humor"],
  ["g6", "h10", "an ordinary kid pulled into a secret magical world"],
  ["g3", "h11", "twists, secrets and deception"],
  ["g2", "h12", "strange, beautiful magic"],
  ["h1", "h13", "animal societies at war"],
  ["g9", "h4", "secret magical worlds with rules to learn"],
  ["g10", "h9", "creepy mysteries full of monsters"],
  ["g11", "h11", "a kid from a hard life proving what he's made of"],
  ["g12", "h9", "funny heroes fighting monsters"],
];

const LEVEL_META = {
  1: { name: "Level 1", ages: "Ages 4–6" },
  2: { name: "Level 2", ages: "Ages 6–8" },
  3: { name: "Level 3", ages: "Ages 7–9" },
  4: { name: "Level 4", ages: "Ages 8–10" },
  5: { name: "Level 5", ages: "Ages 9–11" },
  6: { name: "Level 6", ages: "Ages 10–12" },
  7: { name: "Level 7", ages: "Ages 11–13" },
};

/** Books connected to the given book id, with the reason and direction.
    `dir` is "up" for a harder/older book, "down" for an easier/younger one. */
function connectedTo(id) {
  const out = [];
  CONNECTIONS.forEach(([a, b, why]) => {
    if (a === id) out.push({ id: b, why, dir: "up" });
    else if (b === id) out.push({ id: a, why, dir: "down" });
  });
  return out;
}

/** Look up a book by its id. */
function findBook(id) {
  return SAMPLE_BOOKS.find((b) => b.id === id);
}
